spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: test
      discovery:
        enabled: true
        service-id: config-server
#      uri: http://localhost:8888/

server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
